apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels: { app.kubernetes.io/name: homepage }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: homepage }
  template:
    metadata:
      labels: { app.kubernetes.io/name: homepage }
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: cfg
              mountPath: /app/config
      volumes:
        - name: cfg
          configMap:
            name: homepage
