apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels: { app.kubernetes.io/name: homepage }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: homepage }
  template:
    metadata:
      labels: { app.kubernetes.io/name: homepage }
    spec:
      serviceAccountName: homepage

      # Copy config files into the EXACT path the app reads: /app/config
      initContainers:
        - name: init-config
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              mkdir -p /app/config
              cp -r /config-src/* /app/config/ 2>/dev/null || true
              mkdir -p /app/config/logs
              ls -la /app/config
          volumeMounts:
            - name: cfg-src
              mountPath: /config-src
            - name: cfg
              mountPath: /app/config

      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "localhost:9999,localhost:8888,127.0.0.1:9999,127.0.0.1:8888,localhost,127.0.0.1"
          volumeMounts:
            - name: cfg
              mountPath: /app/config

      volumes:
        # Read-only source from ConfigMap
        - name: cfg-src
          configMap:
            name: homepage
        # Writable target used by both init + app
        - name: cfg
          emptyDir: {}
