apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
  labels: { app.kubernetes.io/name: homepage }
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: homepage }
  template:
    metadata:
      labels: { app.kubernetes.io/name: homepage }
    spec:
      serviceAccountName: homepage

      initContainers:
        - name: init-config
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              echo "[init-config] preparing /app/config ..."
              mkdir -p /app/config

              # 1) Copy from ConfigMap, but DEREFERENCE symlinks (-L) and recurse (-R)
              if [ -d /config-src ] && [ "$(ls -A /config-src 2>/dev/null || true)" ]; then
                echo "[init-config] cp -RL /config-src/* -> /app/config/"
                cp -RL /config-src/* /app/config/ 2>/dev/null || true
              fi

              # 2) Ensure required files exist (fallback to image skeleton)
              for f in settings.yaml services.yaml widgets.yaml kubernetes.yaml; do
                if [ ! -f "/app/config/$f" ]; then
                  echo "[init-config] $f missing; copying from /app/src/skeleton/$f"
                  cp -L "/app/src/skeleton/$f" "/app/config/$f"
                else
                  echo "[init-config] found /app/config/$f"
                fi
              done

              # 3) Ensure writable logs dir
              mkdir -p /app/config/logs
              echo "[init-config] final contents:"
              ls -la /app/config
          volumeMounts:
            - name: cfg-src
              mountPath: /config-src
            - name: cfg
              mountPath: /app/config

      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "localhost:9999,localhost:8888,127.0.0.1:9999,127.0.0.1:8888,localhost,127.0.0.1"
          volumeMounts:
            - name: cfg
              mountPath: /app/config

      volumes:
        - name: cfg-src
          configMap:
            name: homepage
        - name: cfg
          emptyDir: {}
